@startuml
'https://plantuml.com/sequence-diagram

actor       Alice       as Alice
participant Backend as Backend
database    Database    as DB


== Register ==


Alice -> Backend: Register
Backend -> DB : Get les utilisateur avec le même username ou mail
DB -> Backend
alt si il y a une erreur dans le formulaire ou que un utilisateur avec les même identifiant existe
    Backend -> Alice : Error

end
Backend -> DB: on enregistre ses données
Backend -> Alice : redirect sur la page de login

== Login ==

Alice -> Backend: Login
Backend -> DB : Get l'utilisateur avec le même identifiant
DB -> Backend
alt si le mot de passe n'est pas le même que celui hashé (argon2), ou qu'il n'y a aucun utilisateur avec cette identifiant
    Backend -> Alice : Error
end
Backend -> Alice : création d'une websocket




@enduml