@startuml
'https://plantuml.com/deployment-diagram

circle ActeurMonitor
circle Repo
circle GameSimulation


circle GameActor
circle ConnexionActor

ActeurMonitor --> ConnexionActor : créer et stocke un acteur par connexion utilisateur
ActeurMonitor --> GameActor : créer et stocke un acteur par partie en cours avec des utilisateur connecté

GameActor --> ConnexionActor : "retour sur les input utilisateur"
GameActor --> ConnexionActor : "Changement des autre équipes"
GameActor --> ConnexionActor : "Combat"

GameSimulation --> GameActor : retour sur le combat
GameSimulation --> ConnexionActor : envoie du combat

GameActor --> ConnexionActor : Valid/invalidInput
GameActor --> GameSimulation : simulate fight

GameActor --> Repo : persist


@enduml