services:
  postgres:
    image: postgres:16-alpine
    container_name: auto-battler-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - battler-network

  serveur:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto-battler-backend
    restart: unless-stopped

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      APPLICATION_SECRET: ${APPLICATION_SECRET}

    ports:
      - "9000:9000"

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - battler-network



volumes:
  postgres_data:
    driver: local

networks:
  battler-network:
    driver: bridge
