# This is the main configuration file for the application.
# https://www.playframework.com/documentation/latest/ConfigFile
play.http.secret.key="changeme"
play.http.secret.key=${?APPLICATION_SECRET}

db {
  # Default database configuration using PostgreSQL database engine
  default.driver=org.postgresql.Driver
  default.url="jdbc:postgresql://postgres:5432/battler_db"
  default.username=${?DB_USER}
  default.password=${?DB_PASSWORD}
  default.jndiName=DefaultDS
}

# Point JPA at our database configuration
jpa.default=defaultPersistenceUnit

# Makes hibernate only validate tables from the schema already present in postgreSQL
hibernate.hbm2ddl.auto=validate

# db connections = ((physical_core_count * 2) + effective_spindle_count)
fixedConnectionPool = 33 # change it depending on the machine used

# Set Hikari to fixed size
play.db {
  prototype {
    hikaricp.minimumIdle = ${fixedConnectionPool}
    hikaricp.maximumPoolSize = ${fixedConnectionPool}
  }
}

# Job queue sized to HikariCP connection pool
database.dispatcher {
  executor = "thread-pool-executor"
  throughput = 1
  thread-pool-executor {
    fixed-pool-size = ${fixedConnectionPool}
  }
}