# This is the main configuration file for the application.
# https://www.playframework.com/documentation/latest/ConfigFile
play.http.secret.key="changeme"
play.http.secret.key=${?APPLICATION_SECRET}

version=${CURRENT_VERSION}

db {
  # Default database configuration using PostgreSQL database engine
  default.driver=org.postgresql.Driver
  default.url="jdbc:postgresql://postgres:5432/battler_db"
  default.username=${?DB_USER}
  default.password=${?DB_PASSWORD}
  default.jndiName=DefaultDS
}

# Point JPA at our database configuration
jpa.default=defaultPersistenceUnit

# Makes hibernate only validate tables from the schema already present in postgreSQL
hibernate.hbm2ddl.auto=validate

# CSRF filter
play.filters.enabled += "play.filters.csrf.CSRFFilter"

# db connections pool
fixedConnectionPool = 8 # change it depending on the machine used

# Set Hikari to fixed size
play.db {
  prototype {
    hikaricp.minimumIdle = ${fixedConnectionPool}
    hikaricp.maximumPoolSize = ${fixedConnectionPool}
  }
}

# Job queue sized to HikariCP connection pool
database.dispatcher {
  executor = "thread-pool-executor"
  throughput = 1
  thread-pool-executor {
    fixed-pool-size = ${fixedConnectionPool}
  }
}

# pool for cpu bound fight simulation
combat-simulation-dispatcher {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 8
  }
  throughput = 1
}
# HashService configuration those are minimum parameters according to OWASP : https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html
argon2.iterations = 2
argon2.memoryKb = 19456
argon2.parallelism = 1