name: CI

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'

  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t app-test .

      - name: Run tests
        run: |
          docker run --rm app-test \
          sbt clean coverage test coverageReport coverageAggregate

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/scala-*/scoverage-report